FROM kalilinux/kali-rolling

#https://github.com/moby/moby/issues/27988
RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections

# Update + common tools + Install Metapackages https://www.kali.org/docs/general-use/metapackages/

RUN apt-get update; apt-get install -y -q kali-linux-headless

# Default packages

RUN apt-get install -y wget curl net-tools whois netcat-traditional pciutils bmon htop tor

# Kali - Common packages

RUN apt -y install amap \
    apktool \
    arjun \
    beef-xss \
    binwalk \
    cri-tools \
    dex2jar \
    dirb \
    exploitdb \
    kali-tools-top10 \
    kubernetes-helm \
    lsof \
    ltrace \
    man-db \
    nikto \
    set \
    steghide \
    strace \
    theharvester \
    trufflehog \
    uniscan \
    wapiti \
    whatmask \
    wpscan \
    xsser \
    yara

#Sets WORKDIR to /usr

WORKDIR /usr

# XSS-RECON

RUN git clone https://github.com/Ak-wa/XSSRecon; 

# Install language dependencies

RUN apt -y install python3-pip npm nodejs golang

# PyEnv
RUN apt install -y build-essential \
    libssl-dev \
    zlib1g-dev \
    libbz2-dev \
    libreadline-dev \
    libsqlite3-dev \
    llvm \
    libncurses5-dev \
    libncursesw5-dev \
    xz-utils \
    tk-dev \
    libffi-dev \
    liblzma-dev \
    python3-openssl

RUN curl https://pyenv.run | bash

# Set-up necessary Env vars for PyEnv
ENV PYENV_ROOT /root/.pyenv
ENV PATH $PYENV_ROOT/shims:$PYENV_ROOT/bin:$PATH

RUN pyenv install -v 3.7.16; pyenv install -v 3.8.15

# GitHub Additional Tools

# Blackbird
# for usage: blackbird/
# python blackbird.py
RUN /root/.pyenv/versions/3.7.16/bin/python3.7 -m pip install --upgrade pip
RUN git clone https://github.com/p1ngul1n0/blackbird
RUN cd blackbird
RUN pyenv local 3.7.16 && pip install aiohttp==3.9.3, aiosignal==1.3.1, asyncio==3.4.3, attrs==23.2.0, certifi==2024.2.2, chardet==5.2.0 ; \
    charset-normalizer==3.3.2, frozenlist==1.4.1,greenlet==3.0.3,idna==3.6,markdown-it-py==3.0.0,mdurl==0.1.2,multidict==6.0.5,pillow==10.2.0 ; \
    playwright==1.43.0, pyee==11.1.0,Pygments==2.17.2,python-dotenv==1.0.1,reportlab==4.1.0,requests==2.31.0,rich==13.7.1,tdqm==0.0.1 ; \
    typing_extensions==4.11.0,urllib3==2.2.0,yarl==1.9.4
RUN cd ../

# Maigret
# for usage: cd maigret/
# ./maigret.py
RUN git clone https://github.com/soxoj/maigret.git && pyenv local 3.8.15 && pip3 install maigret && cd ../

# Sherlock
# for usage cd sherlock/
# python3 sherlock --help
RUN git clone https://github.com/sherlock-project/sherlock.git && pyenv local 3.8.15  && python3 -m pip install --user sherlock-project &&  cd ../

RUN apt-get clean && \
    rm -rf /var/lib/apt/lists/* 

#############################################################################################################################


COPY docker-entrypoint.sh /

COPY conf/proxychains.conf /etc/proxychains.conf

ENTRYPOINT ["/docker-entrypoint.sh"]